version: '3'

services:
  db:
    image: postgres:13.1-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - education_network

  cache:
    image: redis:7.0.4
    restart: unless-stopped
    networks:
      - education_network
    volumes:
      - .data/cache:/data

  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/education_platform
      - static_volume:/education_platform/static
      - media_volume:/education_platform/media
    expose:
      - 8000
    networks:
      - education_network
    depends_on:
      - db
      - cache

  nginx:
    # image: nginx:1.23.1
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./config/nginx/Dockerfile
    volumes:
      # - ./config/nginx/nginx.conf:/etc/nginx/conf.d
      # - .:/education_platform
      - static_volume:/education_platform/static
      - media_volume:/education_platform/media
      - ./ssl:/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - education_network
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:


networks:
  education_network:
    driver: bridge